###
POST http://localhost:8080/engine/plantuml
content-type: application/json

{
  "fml": "create dim table a (b bigint comment 'comment'); create fact table c (d bigint comment 'c');"
}

###
GET http://localhost:8080/engine/get-image?fml=create dim table a (b bigint comment 'comment'); create fact table c (d bigint comment 'c');a->c;

